// src/routes/decks.routes.ts
import { Router } from 'express';
import * as decksController from '../controllers/decks.controller';
import { authenticateToken } from '../middleware/auth.middleware';

const router = Router();

// Todas las rutas requieren autenticación
router.use(authenticateToken);

// CRUD de decks
router.get('/', decksController.getUserDecks);
router.get('/:id', decksController.getDeck);
router.post('/', decksController.createDeck);
router.put('/:id', decksController.updateDeck);
router.delete('/:id', decksController.deleteDeck);

// Gestión de cartas en el deck
router.get('/:id/cards', decksController.getDeckCards); // Obtener cartas (expandidas)
router.post('/:id/cards', decksController.addCardToDeck);
router.delete('/:id/cards/:card_id', decksController.removeCardFromDeck);
router.put('/:id/cards/:card_id', decksController.updateCardQuantity);
router.put('/:id/sync-cards', decksController.syncDeckCards); // Sincronizar todas las cartas

// Validación y estadísticas
router.get('/:id/validate', decksController.validateDeck);
router.get('/:id/stats', decksController.getDeckStatistics);

// Auto-generación de deck
router.post('/:id/generate', decksController.autoGenerateDeck);

export default router;
